name: Check Indentation

on:
  push:
    branches: [ main ]

jobs:
  check-indentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tidy

    - name: Check indentation
      run: |
        find . -name "*.html" | xargs tidy -q -e
